#!/bin/bash

    echo -e "\n"
        echo "Orphaned packages :"
        pacman -Qtd
            if [[ -n $(pacman -Qtd) ]]; then
                echo -e "\n"
                echo "Remove orphaned packages ?"
                select yn in "Yes" "No"; do
                    case $yn in
                        Yes )
                            echo "Removing orphaned packages..."
                            pacman -Qtdq | sudo pacman -Rns -
                            break;;

                        No ) break;;
                    esac
                done
            else
                echo "No orphaned packages found."
            fi


    exec $(dirname $(dirname $(realpath $0)))/ArchLinux-Maintenance
