#!/bin/bash

    echo -e "\n"
        echo "Orphaned packages :"
        pacman -Qtd
        output="$(pacman -Qtd)"
            if [[ -n $output ]]; then
                echo -e "\n"
                echo "Remove orphaned packages ?"
                select yn in "Yes" "No"; do
                    case $yn in
                        Yes )
                            if [ "$EUID" != 0 ]; then
                            echo "Removing orphaned packages..."
                            pacman -Qtdq | sudo pacman -Rns -
                            else
                            echo "Removing orphaned packages..."
                            pacman -Qtdq | pacman -Rns -
                            fi
                            break;;

                        No ) break;;
                    esac
                done
            else
                echo "No orphaned packages found."
            fi


    exec $(dirname $(dirname $(realpath $0)))/ArchLinux-Maintenance
